feat!: `worker.dev_create_account`, `worker.dev_deploy` create subaccounts of root account instead of tla (sandbox, testnet) (#369)
Renamed method (create_tla) and added .testnet to the randomly generated
ID sent to the helper when creating a dev account

`worker.dev_create_account` has now become `worker.dev_create_tla`,
`worker.dev_deploy` has now become `worker.dev_deploy_tla`

___

- [x] main branch (base branch)
  - [x] sandbox
- [x] creates top level account (`worker.create_tla`,
`worker.create_tla_and_deploy` ,`worker.dev_create_account`,
`worker.dev_deploy`)
    ```bash
    [src/main.rs:18:9] &result = Account {
        id: AccountId(
            "dev-20241224213704-37976876532241",
        ),
    }
    balance = 100.00 NEAR
    ```
  - [x] testnet
    - [x] ERRORs on top level account creation 

    ```bash
    Error: Execution

    Caused by:
Action #0: A top-level account ID
AccountId("dev-20241224215752-62591402306687") can't be created
by AccountId("testnet"), short top-level account IDs can only be created
by AccountId("registrar")
    ```

- [x] remove-using-tla-on-testnet branch (head branch)
  - [x] sandbox
- [x] creates top level account (`worker.create_tla`,
`worker.create_tla_and_deploy`, `worker.dev_create_tla`,
`dev_deploy_tla`)

    ```bash
    [src/main.rs:19:9] &result = Account {
        id: AccountId(
            "dev-20241224222905-84560672890155",
        ),
    }
    balance = 100.00 NEAR
    ```
- [x] creates root account sub-account
(`worker.create_root_account_subaccount`,`
worker.create_root_account_subaccount_and_deploy`,`
worker.dev_create_account`,` worker.dev_deploy`)

    ```bash
    [src/main.rs:35:13] &root_account = Account {
        id: AccountId(
            "test.near",
        ),
    }
    balance = 1000000000.00 NEAR
    [src/main.rs:48:9] &result = Account {
        id: AccountId(
            "dev-20241225121559-79849516817890.test.near",
        ),
    }
    balance = 100.00 NEAR
    ```
  - [x] testnet
- [x] FAILS to compile on top level account creation (no such method)
- [x] creates root account sub-account
(`worker.create_root_account_subaccount`,`
worker.create_root_account_subaccount_and_deploy`,`
worker.dev_create_account`,` worker.dev_deploy`)

    ```bash
    [src/main.rs:62:13] &root_account_id = AccountId(
        "testnet",
    )
    balance = 15561968.34 NEAR
    [src/main.rs:74:9] &result = Account {
        id: AccountId(
            "dev-20241225121906-39307469198620.testnet",
        ),
    }
    balance = 10.01 NEAR
    ```

---------

Co-authored-by: AlexKushnir1 <alex@alex-Precision-7510>
Co-authored-by: dj8yf0μl <noreply@nowhere.org>